### ISSUE TITLE
Question regarding license choice.

### ISSUE THREAD

**Issue by ghost** [ssincak/webmPlayer#2]
Clause 3 of the BSD license has me a bit confused,

https://github.com/time-killer-games/libWebMPlayer/blob/f14c577ff3470f1873bb5de5139da29dd513f266/LICENSE#L18

It sounds like it's telling me I shouldn't credit you, as that is the same as endorsement. But normally people in general appreciate credit so this has me puzzled.

Thus i had to google for clarification.

Then I found this:

https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/

which states:

"This is the clause that prohibits users from using the name of the project to promote their derivative work(s)"

So what i gather from this, I can not mention the software mine derived from, but crediting you is fine as long as I don't mention the original work my work is based on.

Your work's name is very generic. "webmPlayer". I like generic names too, so I chose "libWebMPlayer". Would you like me to rename my library as that really is very close to your library's name? Or is that something you have no means to enforce?

I would like to honor your wishes either way, but I was curious whether something like that can be enforced legally. Seems like borderline endorsement; the similar name.

All of this is very new to me.

Just want to make sure I'm reading all of this correctly.

Thanks!
Samuel

**Comment by ssincak** [comment]
Hi Samuel,

When I made this software public, I wanted to use some ‘normal’ open-source license, which would allow others to use that library even commercially, but with proper credit given. I didn’t think about that third clause that much. Anyway:

- You don’t have to rename your work. I have no means to enforce that.

- Yes I would definitelly appreciate the credit.

I hope the lib will be useful to you, and if You have any more questions let me know.

Have a nice day,
Stefan

**Comment by ghost** [comment]
Thank you! :D
